In [1]:
import numpy as np


def compose_list(row_numb):
    features = []
    total_numb = row_numb * 4
    for i in range(1, total_numb, 4):
        features.append([i, i + 1, i + 2, i + 3])
    return features



def compose_array_by_append(list_of_data):
    array = []
    for i in range(len(list_of_data)):
        data = list_of_data[i]
        array.append(data)
    return array


row_numb = 8
list_of_data = compose_list(row_numb)

arr = compose_array_by_append(list_of_data)
a = np.asarray(arr)
print(a)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


### 按条件过滤第一列数据

In [4]:
a = np.array([
    [0.1, 1, 3, 4],
    [0.11, 2, 3, 4],
    [0.91, 3, 3, 4],
    [0.31, 4, 3, 4],
    [0.51, 5, 3, 4],
    [0.21, 6, 3, 4],
], dtype=np.float32)
b= a[np.where((a[:,0] > 0.2) & (a[:,1] > 4))]
b


array([[0.51, 5.  , 3.  , 4.  ],
       [0.21, 6.  , 3.  , 4.  ]], dtype=float32)

In [14]:
all_data = np.load('all_features.npy')
len(all_data)
all_data.ndim

all_data[1:5,:]


array([[0., 1., 0.],
       [0., 2., 0.],
       [0., 3., 0.],
       [0., 4., 0.]], dtype=float32)

In [12]:
all_data[np.where((all_data[:,0] > 0.015))]

array([], shape=(0, 3), dtype=float32)

In [ ]:
a = math.ceil(3.4)
print(a)