In [40]:
from math import floor

test_len = 12
fbt_array = [
    [0,   0, 100, 112],
    [1, 113, 156, 168],
    [2, 168, 230, 242],
    [3, 245, 360, 372],
    [4, 373, 700, 712]]

def is_valid_idx(idx, data):
    bottom_index =  len(data) - 1
    if bottom_index < 0:
        return False
    if idx >= data[bottom_index][3]:
        return False
    
    top_index = 0 
    while top_index <= bottom_index:        
        mid_index = top_index + floor((bottom_index - top_index) // 2)
        mid_val = data[mid_index][1]
#         print('%d (%d  %d) mid_i=%d  mid_v=%d' % (idx, top_index, bottom_index, mid_index, mid_val))
        if mid_val <= idx <= data[mid_index][2]:
            return True
        elif data[mid_index][2] < idx <= data[mid_index][3]:
            return False
        elif idx < mid_val:
            bottom_index = mid_index
        elif idx > mid_val:
            top_index = mid_index + 1
 
# 373 (3  4) mid_i=3  mid_v=245
        
r = is_valid_idx(0, fbt_array)        
print(r == True)

        
r = is_valid_idx(100, fbt_array)        
print(r == True)

        
r = is_valid_idx(112, fbt_array)        
print(r == False)

r = is_valid_idx(156, fbt_array)   
print(r)


r = is_valid_idx(373, fbt_array)   
print(r)



r = is_valid_idx(374, fbt_array)   
print(r)



r = is_valid_idx(700, fbt_array)   
print(r)


r = is_valid_idx(710, fbt_array)   
print(r == False)

r = is_valid_idx(712, fbt_array)   
print(r == False)

r = is_valid_idx(713, fbt_array)   
print(r == False)



True
True
True
True
False
False
False
True
True
True


In [41]:


fbt_array = [
    [0,   0, 100, 112],
    [1, 113, 156, 168]]


r = is_valid_idx(0, fbt_array)        
print(r)

        
r = is_valid_idx(100, fbt_array)        
print(r)

        
r = is_valid_idx(101, fbt_array)        
print(r == False)
        
r = is_valid_idx(112, fbt_array)        
print(r == False)

r = is_valid_idx(156, fbt_array)   
print(r)


r = is_valid_idx(157, fbt_array)   
print(r == False )



True
True
True
True
True
True


In [58]:
import numpy as np

fbt = [
    [0,   0, 100, 112],
    [1, 113, 156, 168],
    [2, 168, 230, 242],
    [3, 245, 360, 372],
    [4, 373, 700, 712]]

a = np.asarray(fbt, dtype=np.int32)
b = a.copy()
print(a)
print(b)

b = b[:, 1] + 100
print(b)

[[  0   0 100 112]
 [  1 113 156 168]
 [  2 168 230 242]
 [  3 245 360 372]
 [  4 373 700 712]]
[[  0   0 100 112]
 [  1 113 156 168]
 [  2 168 230 242]
 [  3 245 360 372]
 [  4 373 700 712]]
[100 213 268 345 473]


In [60]:
a = np.array([
       [8, 1, 0, 8],
       [1, 4, 8, 8],
       [7, 8, 7, 6],
       [8, 7, 6, 5]])
(rowa,cola)=np.where(a==np.max(a,axis=0))  # 每列最大元素的索引
(rowa,cola)

(array([0, 0, 1, 1, 2, 3]), array([0, 3, 2, 3, 1, 0]))